name: Auto Build and Release

on: [push]

jobs:
  build_app:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20.9.0
        uses: actions/setup-node@v4
        with:
          node-version: 20.9.0

      - name: Install Dependencies
        run: npm install

      - name: Build App
        run: npm run build

      - name: Archive App
        run: npm run pack

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: dist