name: Auto Build and Release

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_app:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20.9.0
        uses: actions/setup-node@v4
        with:
          node-version: 20.9.0

      - name: Install Dependencies
        run: npx pnpm install

      - name: Build App
        run: npx pnpm build:mac

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: dist